### ISSUE TITLE
After trying to place a lay bet with stake of 2.01 and odds of 1.99, I get: Order Creation: decimal limit breached for market

### ISSUE THREAD

**Issue by lbianlbian** [MonacoProtocol/protocol#34]
The market takes tether: G8wcjgQDkd6E1qqnSnPNFT5TaQEPpRCyfpmMJunREVgE
I am using the javascript client SDK, and the method I am using is createOrderUiStake.
Neither 2.01 nor 1.99 are over 9 decimal places (USDT decimal places), and the amount leaving my wallet would be 2.01 * 0.99 = 1.9899, which is not over 9 decimal places. When running 2.01 * 0.99 in javascript, I get 1.9898999999999998, which I assume is the issue. 
If the issue is on my end, is there something I need to do to the parameters I pass into createOrderUiStake in order to make it work in this scenario? And if the issue is with the SDK, could you guys fix it, and when do you think it could be fixed?
Thanks in advance.

**Comment by lbianlbian** [comment]
correction, tether has 6 decimal places.

**Comment by eoin-betdex** [comment]
Hi @lbianlbian. Thanks for spotting this. Yes, it's an issue within the javascript client. Specifically within `uiStakeToInteger` where e.g., 2.01 _should be_ transformed into 2010000 but instead is returning `2009999.9999999998` which indeed does breach the decimals limit for the market. 

For now, you could do that transformation yourself and make use of `createOrder` instead. We'll look at a fix today for the issue though.

**Comment by eoin-betdex** [comment]
Hi @lbianlbian hopefully this has been solved with #36 and the subsequent release of client version 3.0.1. Please do note here if the issue is resolved or it persists after you upgrade your monaco client dependency.

**Comment by lbianlbian** [comment]
Thanks for responding. Unfortunately I think something might have broken with the update. 
I updated @monaco-protocol/client to 3.0.1. I tried the following and all gave me this error:
Laying 2.01 at 1.99
Laying 1 at 1.51
Laying 1 at 1.5
Laying 1 at 1.49
(node:5864) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'stakeInteger' of undefined

**Comment by lbianlbian** [comment]
Here's some more of the stack trace if it helps
at Object.<anonymous> (XXXXXXX\@monaco-protocol\client\src\create_order.js:90:130)
    at step (XXXXXXXX\@monaco-protocol\client\src\create_order.js:33:23)
    at Object.next (XXXXXXXX\@monaco-protocol\client\src\create_order.js:14:53)
    at fulfilled (XXXXXXXX\@monaco-protocol\client\src\create_order.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)

**Comment by lbianlbian** [comment]
Sorry, I had the market address wrong. I just tried laying 2.01 tether at 1.99 and it went through. Thanks for fixing it
